var sections = {
    "MYMEDICARE.GOV PERSONAL HEALTH INFORMATION": null,
    "Demographic": require('./sections/demographics.js'),
    "Emergency Contact": require('./sections/problems.js'),
    "Self Reported Medical Conditions": null,
    "Self Reported Allergies": null,
    "Self Reported Implantable Device": null,
    "Self Reported Immunizations": null,
    "Self Reported Labs and Tests": null,
    "Self Reported Vital Statistics": null,
    "Family Medical History": null,
    "Drugs": null,
    "Preventive Services": null,
    "Providers": null,
    "Pharmacies": null,
    "Plans": null,
    "Employer Subsidy": null,
    "Primary Insurance": null,
    "Other Insurance": null,
    "Claim Summary": null
};
