var libxmljs = require("libxmljs");


function writeXML(sectionNumber, data, codeSystems) {
    var xml = {};
    if (sectionNumber == 2) {
        xml = loadMedications(sectionNumber, data, codeSystems);
    }
    return xml;
}


function loadMedications(sectionNumber, data, codeSystems) {
     // determining the number of entries
    var entriesArr = [];
    var entries = {};
    for (var i = 0; i < data.length; i++) {
        entriesArr[i] = data[i]["date"][0][0]["date"].slice(0,4);
        entries[entriesArr[i]] = i + 1;
    }
    var uniqueEntries = entriesArr.filter(function(v,i) { return i == entriesArr.lastIndexOf(v); });

    for (var i = 1; i < uniqueEntries.length; i++) {
        entries[uniqueEntries[i]] = entries[uniqueEntries[i]] - entries[uniqueEntries[i-1]];
    }

    // allergy problem act
    var doc = new libxmljs.Document();
    var xmlDoc = doc.node('ClinicalDocument').attr({"xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"})
        .attr({xmlns: "urn:hl7-org:v3"}).attr({"xmlns:cda": "urn:hl7-org:v3"}).attr({"xmlns:sdtc": "urn:hl7-org:sdtc"})
        .node('section')
            .node('templateID').attr({root: "2.16.840.1.113883.10.20.22.2.1"}).parent()
            .node('templateID').attr({root: "2.16.840.1.113883.10.20.22.2.1.1"}).parent()
            .node('code').attr({code: "10160-0" })
                .attr({codeSystem: "2.16.840.1.113883.6.1"})
                .attr({codeSystemName: "LOINC"})
                .attr({displayName: "HISTORY OF MEDICATION USE"}).parent()
            .node('title', "MEDICATIONS").parent()
            .node('text').parent()

            // entries loop
            for (var i = 0; i < uniqueEntries.length; i++) {
                var timeArr = [];
                for (var k = 0; k < data[i]["date"][0].length; k++) {
                    var effectiveTime = data[i]["date"][0][k]["date"].split("-");
                    effectiveTime[2] = effectiveTime[2].slice(0,2);
                    var time = effectiveTime[0] + effectiveTime[1] + effectiveTime[2];
                    timeArr.push(time);
                }
                var organizer = xmlDoc.node('entry').attr({typeCode: "DRIV"})
                                      .node('substanceAdministration').attr({classCode: "SBADM"}).attr({moodCode: "EVN"});

                    // medication activity
                    organizer.node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.16"}).parent()
                        .node('id').attr({root: data[0]["identifiers"][0]["identifier"]}).parent()
                        .node('text', data[i]["product"]["unencoded_name"])
                            .node('reference').attr({value: "#MedSec_1"}).parent()
                        .parent()
                        .node('statusCode').attr({code: 'completed'}).parent()
                        .node('effectiveTime').attr({"xsi:type": "IVL_TS" })
                            .node('low').attr({value: timeArr[0]}).parent()
                            .node('high').attr({value: timeArr[1]}).parent()
                        .parent()
                        .node('effectiveTime').attr({"xsi:type": "PIVL_TS" })
                                              .attr({institutionSpecified: "true"})
                                              .attr({operator: "A"})
                            .node('period').attr({value: "6"}).attr({unit: "h"}).parent()
                        .parent()
                        .node('routeCode').attr({code: data[i]['administration']['route']['code']})
                                          .attr({codeSystem: "2.16.840.1.113883.3.26.1.1"})
                                          .attr({codeSystemName: data[i]["administration"]["route"]["code_system_name"]})
                                          .attr({displayName: data[i]["administration"]["route"]["name"]}).parent()
                        .node('doseQuantity').attr({value: data[i]["administration"]["dose"]["value"]})
                                             .attr({unit: data[i]["administration"]["dose"]["unit"]}).parent()
                        .node('rateQuantity').attr({value: data[i]["administration"]["rate"]["value"]})
                                             .attr({unit: data[i]["administration"]["rate"]["unit"]}).parent()
                        .node('maxDoseQuantity').attr({nullFlavor: "UNK"})
                            .node('numerator').attr({nullFlavor: "UNK"}).parent()
                            .node('denominator').attr({nullFlavor: "UNK"}).parent()
                        .parent()
                        .node('administrationUnitCode').attr({code: data[i]["administration"]["form"]["code"]})
                                                     .attr({displayName: data[i]["administration"]["form"]["name"]})
                                                     .attr({codeSystem: "2.16.840.1.113883.3.26.1.1"})
                                                     .attr({codeSystemName: data[i]["administration"]["form"]["code_system_name"]}).parent()
                        .node('consumable')
                            .node('manufacturedProduct').attr({classCode: "MANU"}) // medication information
                                .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.23"}).parent()
                                .node('id').attr({root: data[i]["product"]["identifiers"]["identifier"]}).parent()
                                .node('manufacturedMaterial')
                                    .node('code').attr({code: data[i]["product"]["code"]})
                                                 .attr({codeSystem: "2.16.840.1.113883.6.88"})
                                                 .attr({displayName: data[i]["product"]["name"]})
                                        .node('originalText')
                                            .node('reference').attr({value: '#MedSec_1'}).parent()
                                        .parent()
                                        .node('translation').attr({code: data[i]["product"]["translations"][0]["code"]})
                                                            .attr({displayName: data[i]["product"]["translations"][0]["name"]})
                                                            .attr({codeSystem: codeSystems[data[i]["product"]["code_system_name"]]})
                                                            .attr({codeSystemName: data[i]["product"]["code_system_name"]}).parent()
                                    .parent()
                                .parent()
                                .node('manufacturerOrganization')
                                    .node('name', "Medication Factory Inc.").parent()
                                .parent()
                            .parent()
                        .parent()
                        .node('performer')
                            .node('assignedEntity')
                                .node('id').attr({nullFlavor: "NI"}).parent()
                                .node('addr').attr({nullFlavor: "UNK"}).parent()
                                .node('telecom').attr({nullFlavor: "UNK"}).parent()
                                .node('representedOrganization')
                                    .node('id').attr({root: "2.16.840.1.113883.19.5.9999.1393"}).parent()
                                    .node('name', "Community Health and Hospitals").parent()
                                    .node('telecom').attr({nullFlavor: "UNK"}).parent()
                                    .node('addr').attr({nullFlavor: "UNK"}).parent()
                                .parent()
                            .parent()
                        .parent()
                        .node('participant').attr({typeCode: "CSM"})
                            .node('participantRole').attr({classCode: "MANU"}) // drug vehicle
                                .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.24"}).parent()
                                .node('code').attr({code: "412307009"})
                                             .attr({displayName: "drug vehicle"})
                                             .attr({codeSystem: "2.16.840.1.113883.6.96"}).parent()
                                .node('playingEntity').attr({classCode: "MMAT"})
                                    .node('code').attr({code: "324049"}) // TODO: PERFORM LOOKUP??
                                                 .attr({displayName: "Aerosol"})
                                                 .attr({codeSystem: "2.16.840.1.113883.6.88"})
                                                 .attr({codeSystemName: "RxNorm"}).parent()
                                    .node('name', "Aerosol").parent()
                                .parent()
                            .parent()
                        .parent()
                        .node('entryRelationship').attr({typeCode: "RSON"})
                            .node('observation').attr({classCode: "OBS"}).attr({moodCode: "EVN"}) // Indication
                                .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.19"}).parent()
                                .node('id').attr({root: "db734647-fc99-424c-a864-7e3cda82e703"})
                                           .attr({extension: "45665"}).parent()
                                .node('code').attr({code: "404684003"})
                                             .attr({displayName: "Finding"})
                                             .attr({codeSystem: codeSystems["SNOMED CT"][0]})
                                             .attr({codeSystemName: "SNOMED CT"}).parent()
                                .node('statusCode').attr({code: "completed"}).parent()
                                .node('effectiveTime')
                                    .node('low').attr({value: time}).parent()
                                .parent()
                                .node('value').attr({"xsi:type": "CD"})
                                              .attr({code: "233604007"})
                                              .attr({displayName: "Pneumonia"})
                                              .attr({codeSystem: "2.16.840.1.113883.6.96"}).parent()
                            .parent()
                        .parent()
                        .node('entryRelationship').attr({typeCode: "REFR"})
                            .node('supply').attr({classCode: "SPLY"}).attr({moodCode: "INT"})
                                .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.17"}).parent()
                                .node('id').attr({nullFlavor: "NI"}).parent()
                                .node('statusCode').attr({code: "completed"}).parent()
                                .node('effectiveTime').attr({"xsi:type": "IVL_TS"})
                                    .node('low').attr({value: timeArr[0]}).parent()
                                    .node('high').attr({value: timeArr[1]}).parent()
                                .parent()
                                .node('repeatNumber').attr({value: "1"}).parent()
                                .node('quantity').attr({value: "75"}).parent()
                                .node('product')
                                    .node('manufacturedProduct').attr({classCode: "MANU"}) // medication information
                                        .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.23"}).parent()
                                        .node('id').attr({root: "2a620155-9d11-439e-92b3-5d9815ff4ee8"}).parent()
                                        .node('manufacturedMaterial')
                                            .node('code').attr({code: data[i]["product"]["translations"][0]["code"]})
                                                         .attr({codeSystem: codeSystems[data[i]["product"]["translations"][0]["code_system_name"]]})
                                                         .attr({displayName: data[i]["product"]["translations"][0]["name"]})
                                            .node('originalText')
                                                .node('reference').attr({value: '#MedSec_1'}).parent()
                                            .parent()
                                            .node('translation').attr({code: data[i]["product"]["translations"][0]["code"]})
                                                                .attr({displayName: data[i]["product"]["translations"][0]["name"]})
                                                                .attr({codeSystem: codeSystems[data[i]["product"]["translations"][0]["code_system_name"]]})
                                                                .attr({codeSystemName: data[i]["product"]["translations"][0]["code_system_name"]}).parent()
                                            .parent()
                                        .parent()
                                        .node('manufacturerOrganization')
                                            .node('name', "Medication Factory Inc.").parent()
                                        .parent()
                                    .parent()
                                .parent()
                                .node('performer')
                                    .node('assignedEntity')
                                        .node('id').attr({extension: "2981823"}).attr({root: "2.16.840.1.113883.19.5.9999.456"}).parent()
                                        .node('addr')
                                            .node('streetAddressLine', '1001 Village Avenue').parent()
                                            .node('city', 'Portland').parent()
                                            .node('state', 'OR').parent()
                                            .node('postalCode', '99123').parent()
                                            .node('country', 'US').parent()
                                        .parent()
                                    .parent()
                                .parent()
                                .node('author')
                                    .node('time').attr({nullFlavor: "UNK"}).parent()
                                    .node('assignedAuthor')
                                        .node('id').attr({root: data[i]["product"]["identifiers"]["identifier"]}).parent()
                                        .node('addr').attr({nullFlavor: "UNK"}).parent()
                                        .node('telecom').attr({nullFlavor: "UNK"}).parent()
                                        .node('assignedPerson')
                                            .node('name')
                                                .node('prefix', "Dr.").parent()
                                                .node('given', "Henry").parent()
                                                .node('family', 'Seven').parent()
                                            .parent()
                                        .parent()
                                    .parent()
                                .parent()
                                .node('entryRelationship').attr({typeCode: "SUBJ"}).attr({inversionInd: "true"})
                                    .node('act').attr({classCode: "ACT"}).attr({moodCode: "INT"})
                                        .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.20"}).parent()
                                        .node('code').attr({code: "409073007"})
                                             .attr({codeSystem: "2.16.840.1.113883.6.96"})
                                             .attr({displayName: "instruction"}).parent()
                                        .node('text', 'label in spanish')
                                            .node('reference').attr({value: "#MedSec_1"}).parent()
                                        .parent()
                                        .node('statusCode').attr({code: "completed"}).parent()
                                    .parent()
                                .parent()
                            .parent()
                        .parent()
                        .node('entryRelationship').attr({typeCode: "REFR"})
                            .node('supply').attr({classCode: "SPLY"}).attr({moodCode: "EVN"}) // medication dispense
                                .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.18"}).parent()
                                .node('id').attr({root: "1.2.3.4.56789.1"}).attr({extension: "cb734647-fc99-424c-a864-7e3cda82e704"}).parent()
                                .node('statusCode').attr({code: "completed"}).parent()
                                .node('effectiveTime').attr({value: timeArr[0]}).parent()
                                .node('repeatNumber').attr({value: "1"}).parent()
                                .node('quantity').attr({value: "75"}).parent()
                                .node('product')
                                    .node('manufacturedProduct').attr({classCode: "MANU"}) // medication information
                                        .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.23"}).parent()
                                        .node('id').attr({root: "2a620155-9d11-439e-92b3-5d9815ff4ee8"}).parent()
                                        .node('manufacturedMaterial')
                                            .node('code').attr({code: data[i]["product"]["translations"][0]["code"]})
                                                         .attr({codeSystem: codeSystems[data[i]["product"]["translations"][0]["code_system_name"]]})
                                                         .attr({displayName: data[i]["product"]["translations"][0]["name"]})
                                            .node('originalText')
                                                .node('reference').attr({value: '#MedSec_1'}).parent()
                                            .parent()
                                            .node('translation').attr({code: data[i]["product"]["translations"][0]["code"]})
                                                                .attr({displayName: data[i]["product"]["translations"][0]["name"]})
                                                                .attr({codeSystem: codeSystems[data[i]["product"]["translations"][0]["code_system_name"]] })
                                                                .attr({codeSystemName: data[i]["product"]["code_system_name"]}).parent()
                                            .parent()
                                        .parent()
                                        .node('manufacturerOrganization')
                                            .node('name', "Medication Factory Inc.").parent()
                                        .parent()
                                    .parent()
                                .parent()
                                .node('performer')
                                    .node('time').attr({nullFlavor: "UNK"}).parent()
                                    .node('assignedEntity')
                                        .node('id').attr({root: "2.16.840.1.113883.19.5.9999.456"})
                                                    .attr({extension: "2981823"}).parent()
                                        .node('addr')
                                            .node('streetAddressLine', '1001 Village Avenue').parent()
                                            .node('city', 'Portland').parent()
                                            .node('state', 'OR').parent()
                                            .node('postalCode', '99123').parent()
                                            .node('country', 'US').parent()
                                        .parent()
                                        .node('telecom').attr({nullFlavor: "UNK"}).parent()
                                        .node('assignedPerson')
                                            .node('name')
                                                .node('prefix', "Dr.").parent()
                                                .node('given', "Henry").parent()
                                                .node('family', 'Seven').parent()
                                            .parent()
                                        .parent()
                                        .node('representedOrganization')
                                            .node('id').attr({root: "2.16.840.1.113883.19.5.9999.1393"}).parent()
                                            .node('name', "Community Health and Hospitals").parent()
                                            .node('telecom').attr({nullFlavor: "UNK"}).parent()
                                            .node('addr').attr({nullFlavor: "UNK"}).parent()
                                        .parent()
                                    .parent()
                                .parent()
                            .parent()
                        .parent()
                        .node('precondition').attr({typeCode: "PRCN"}) // precondition for substance administration
                            .node('templateId').attr({root: "2.16.840.1.113883.10.20.22.4.25"}).parent()
                            .node('criterion')
                                .node('code').attr({code: data[i]["precondition"]["code"]["code"]})
                                             .attr({codeSystem: "2.16.840.1.113883.5.4"}).parent()
                                .node('value').attr({"xsi:type": "CE"})
                                              .attr({code: data[i]["precondition"]["value"]["code"]})
                                              .attr({codeSystem: "2.16.840.1.113883.6.96"})
                                              .attr({displayName: "Wheezing"}).parent()
                            .parent()
                        .parent()
            
        xmlDoc.parent()
            .parent()
    }   
    xmlDoc.parent() // end section
        .parent(); // end clinicalDocument
    return doc;
}

module.exports = function() {
    return writeXML(arguments["0"], arguments["1"], arguments["2"]);
}

